#!/usr/bin/env bash

docker run \
    --rm \
    -e ACCEPT_EULA=true \
    --net=host \
    -v $PWD:$PWD \
    parasoft/soavirt \
    soatestcli "$@"
soatestStatus=$?

docker run \
    --rm \
    -e ACCEPT_EULA=true \
    --net=host \
    -v $PWD:$PWD \
    parasoft/soavirt \
    chmod -fR go+rw "$PWD/target/soatest"

exit ${soatestStatus}
